### ISSUE TITLE
i tried to download qgis get 404 error on 3.36 and LTR 3.34 download links

### ISSUE THREAD

**Issue by marcuslindh** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1248] opened 2024-05-24 09:37 UTC
## Description
I tried to download some version of qgis and I just get 404 error

Page URL: https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.36.3-1.msi?US
![image](https://github.com/qgis/QGIS-Website/assets/5172807/4f4bf9c1-3593-4f23-97be-95475b67b3dd)

**Comment by pathmapper** [comment] 2024-05-24 10:21
Confirmed, 3.36.3 isn't available here: https://download.osgeo.org/qgis/windows/

**Comment by agiudiceandrea** [comment] 2024-05-26 19:36
@marcuslindh @pathmapper, it looks like it's fixed now.

**Closed as completed** 2024-07-29 18:51 UTC
