### ISSUE TITLE
Clipper function error: I want to clip composite landsat images, but when I use Raster/Extraction/Clipper, and draw a box to select area, and click OK, I have "ERROR 1: SDTS driver has no creation capabilities".  I reinstalled QGIS, but still have same error. Please help me.

### ISSUE THREAD

**Issue by jiyulchang** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#506] opened 2018-03-10 22:00 UTC
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment] 2018-03-11 07:30
Dear @jiyulchang,

This repo is about issues found when browsing the QGIS website, not about QGIS software. For issues around the application, please use the issue tracker https://issues.qgis.org/ (if it's confirmed as a bug) or any of the support channels available from https://www.qgis.org/en/site/forusers/support.html or https://www.qgis.org/en/site/forusers/commercial_support.html

I am closing this issue, because it is at the wrong repo.
Thanks for understanding.

**Closed as completed by DelazJ** 2018-03-11 07:30 UTC
