### ISSUE TITLE
Contact link not working (404 Not Found)

### ISSUE THREAD

**Issue by zambra** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#367] opened 2016-07-18 18:43 UTC
The envelope image link is broken at the bottom of the main page (just after the Github image). The link points to [http://www.qgis.org/en/site/getinvolved/about.html](url)

**Comment by rduivenvoorde** [comment] 2016-07-23 20:48
Mmm, thanks for noting, will have a look at it

**Comment by DelazJ** [comment] 2016-10-11 19:56
Duplicate of #377 and fixed in #378

**Closed as completed** 2016-10-11 19:56 UTC
