### ISSUE TITLE
Mac QGIS version 3.16.2 not on website or outdated link?

### ISSUE THREAD

**Issue by Trigonatus** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#852] opened 2020-12-29 00:01 UTC
On this page:
https://qgis.org/en/site/forusers/download.html
The hyperlink for the text:
"QGIS macOS Installer Version 3.16" -  links to version 3.16.1 it should link to 3.16.2.
Please fix this.
Thank you.

**Comment by rduivenvoorde** [comment] 2020-12-29 08:29
For what I can see, there is no 3.16.2 yet @PeterPetrik ?. I cannot check for real, as I do not have a mac and there is not version number in the files, but there is no file with a recent creation date...

Building of install packages is done on voluntary basis, so please be patient.

**Comment by Trigonatus** [comment] 2020-12-29 15:15
While in QGIS - select from the menu "Help"  and then "Check QGIS Version" 
Was able to install the Windows 3.16.2 version using this method. However, the link for the MAC version is still 3.16.1 it should be 3.16.2. Perhaps I'm missing something?
![Screen Shot 2020-12-29 at 10 07 54 AM](https://user-images.githubusercontent.com/29109635/103293900-c4d77300-49be-11eb-9028-21e3f7eaf385.jpg)

**Comment by PeterPetrik** [comment] 2021-01-01 13:24
link on web is ok, just package in not yet created. this is duplicate of https://github.com/qgis/QGIS-Mac-Packager/issues/106

**Comment by Trigonatus** [comment] 2021-01-01 16:35
Peter, 
Thanks for the information. 
Perhaps it would cause less confusion if on the website it stated that version 3.16.x for the macOS is not yet available.

**Comment by agiudiceandrea** [comment] 2021-01-07 21:29
QGIS 3.16.2 for macOS is now available.

**Comment by Trigonatus** [comment] 2021-01-10 14:11
Thank you!

**Comment by agiudiceandrea** [comment] 2021-01-10 15:13
So, you can close this issue.

**Closed as completed** 2021-01-10 15:16 UTC

**Comment by Trigonatus** [comment] 2021-01-30 17:11
Hi,

How does one know when a new macOS build is available for download? Is it stated on the website?

Thank you,
John

**Comment by PeterPetrik** [comment] 2021-02-01 08:50
You can always check in the download area directly https://qgis.org/downloads/macos/ when the last file was produced. The link on the website only refers to the "latest" in that folder
