### ISSUE TITLE
GPG Key for Ubuntu 16.04 Repository Expired

### ISSUE THREAD

**Issue by brotherdust** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#664] opened 2019-08-22 20:59 UTC
## Description
Followed guide here: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

GPG key, signature `CAEB3DC3BDF7FB45` is expired for Ubuntu 16.04 package repo. Here's the output from `apt`:
```
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                         Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                       Get:5 https://qgis.org/ubuntu xenial InRelease [3344 B]                                                                 Err:5 https://qgis.org/ubuntu xenial InRelease                                                                            The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
Reading package lists... Done                                                                                           W: GPG error: https://qgis.org/ubuntu xenial InRelease: The following signatures were invalid: EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
E: The repository 'https://qgis.org/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please be advised that the key expired on August 16th, 2019.

**Comment by ljrox** [comment] 2019-08-23 07:43
Hello,
I've the same problem with Debian 9 (Stretch), so it's not only Ubuntu :

`W: Erreur de GPG : https://qgis.org/debian stretch InRelease : Les signatures su                                                           ivantes ne sont pas valables : EXPKEYSIG CAEB3DC3BDF7FB45 QGIS Archive Automatic                                                            Signing Key (2017) <qgis-developer@lists.osgeo.org>
W: The repository 'https://qgis.org/debian stretch InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potential                                                           ly dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                                           ils.`

**Comment by laurentj** [comment] 2019-08-27 15:27
Try to install the new key, as indicated into the documentation : https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

```
wget -O - https://qgis.org/downloads/qgis-2019.gpg.key | gpg --import
gpg --export --armor 51F523511C7028C3 | sudo apt-key add -
```

**Comment by jef-n** [comment] 2019-09-01 19:30
Duplicate of #666

**Closed as completed by jef-n** 2019-09-01 19:30 UTC
