### ISSUE TITLE
QGIS Archive Automatic Signing Key (2019) expired [2020-08-08]

### ISSUE THREAD

**Issue by Juma7C9** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#797] opened 2020-08-08 12:41 UTC
Hi all,

As of today the key used to sign packages (at least on the Debian/Ubuntu) repository is expired, so the installation/update fails.

Please renew or update the key, and if necessary modify the documentation accordingly.

Regards :)

**Comment by jef-n** [comment] 2020-08-09 00:36
Duplicate of qgis/QGIS#38204

**Closed as completed by jef-n** 2020-08-09 00:36 UTC
