### ISSUE TITLE
QGIS Version 3.34 download not available for Mac

### ISSUE THREAD

**Issue by bsousa22** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1203] opened 2023-11-08 14:02 UTC
## Description

On the downloads page of the site, it says that the current version of QGIS is 3.34.0 'Prizren'. 

![Screenshot 2023-11-08 at 9 01 25 AM](https://github.com/qgis/QGIS-Website/assets/69688117/c0c9557d-7fc9-48b0-81ea-b4b27d534ad1)

However, when I go to download it for MacOS, QGIS version 3.32 is the one that is available. 

![Screenshot 2023-11-08 at 9 01 42 AM](https://github.com/qgis/QGIS-Website/assets/69688117/21246870-2db8-422f-9646-04f36e5d850d)

I was hoping that this would be able to be updated to reflect the current version of 3.34.

Thank you!

Page URL: https://qgis.org/en/site/forusers/download.html

**Comment by agiudiceandrea** [comment] 2023-11-12 14:34
The issue is fixed now.
https://github.com/qgis/QGIS-Website/commit/eb27639925a30f1cb76b39690ffcc32e11a04f3d
https://github.com/qgis/QGIS-Mac-Packager/commit/ec2fd5d4bf7ac232e773758d9d4b4344408edacb
https://github.com/qgis/QGIS-Mac-Packager/commit/7431116e89796a991f90ead2946a99057eab560f

![image](https://github.com/qgis/QGIS-Website/assets/16253859/aec075e4-d933-4f5b-8db3-c38f8d421c42)
![image](https://github.com/qgis/QGIS-Website/assets/16253859/30a6cc48-6b0d-4199-8557-1d63ee2b1c36)

**Closed as completed** 2023-11-12 14:49 UTC
