### ISSUE TITLE
gdal issue in QGIS3.4.14:"No module named gdal_merge" in Win10

### ISSUE THREAD

**Issue by masterpigis** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#708] opened 2019-12-25 17:12 UTC
![merge](https://user-images.githubusercontent.com/59229649/71447809-9ed81c80-2733-11ea-9e1f-8ca9738de494.JPG)
the existing solution of the former similar issue (https://trac.osgeo.org/osgeo4w/ticket/588) sofar is not applicable for this case, also all the other possible solutions were tried out but didnt work, including:
-numpy reinstalled and the latestes update 
-environmental variable checked and reset

would appreciate for the help!

**Comment by DelazJ** [comment] 2019-12-26 16:34
Hi
@masterpigis Please ask for help in qgis-user list (see [support channels](http://qgis.org/en/site/forusers/support.html)) or report the issue in the [application repository](https://github.com/qgis/QGIS/issues) with detailed steps. But first, also update to recent versions (3.4.14 or 3.10), maybe the issue is fixed.
This repository is actually dedicated to issues related to the [main website](https://qgis.org) of QGIS project. I'm closing. Thanks.

**Closed as completed by DelazJ** 2019-12-26 16:34 UTC
