### ISSUE TITLE
CRS Error

### ISSUE THREAD

**Issue by Algarius** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#857] opened 2021-01-08 15:00 UTC
Hello 
Firtst of all sorry for my bad english. But i am a german.

Im new on QGIS, and i have a question. I downloaded the Natural Earth TIFF 
https://www.naturalearthdata.com/downloads/10m-raster-data/
I import this Tiff in Qgis Version 3.16.2
Then i change the KBS ( I think in english its the name CRS) to
World_times (ESRI: 54048) or to Sphere_times (ESRI: 53048)
but when i do this, the Map disappear and i have a white blank screen instead of the Map.

Have you an idea waht i doing wrong?

Thank you very much for your Help
Best regards
Thomas

**Comment by rduivenvoorde** [comment] 2021-01-08 15:11
@Algarius sorry, this issue tracker is for the QGIS website only. So I'm going to close it here.

When I load your data, and then change the project crs to one of the ones you mentioned all is fine. So I cannot reproduce your issue.

If you have questions, like this (which does not seem to be a QGIS Bug), please use the mailing lists

To learn about basics of QGIS (im Deutch):
https://www.qgis.org/de/docs/index.html

There is also https://fossgis.de/ the German OpenSource GIS community with some very helpfull German speaking people.

**Closed as completed by rduivenvoorde** 2021-01-08 15:11 UTC
